config/routes.rb
Rails.application.routes.draw do
  resources :articles

  get "welcome/index"
  root "welcome#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end
    def new
        @article = Article.new
    end
    def show
        @article = Article.find(params[:id])
    end
    def create
        @article = Article.new(article_params)
        @article.save

        if @article.save
            redirect_to @article    
        else
            render 'new'
        end
    end

    private
    def article_params
        params.require(:article).permit(:title, :text)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/index.html.erb
<h1>Listing Articles</h1>

<%= link_to 'New article', new_article_path %>
<table>
    <tr>
        <th>Title</th>
        <th>Text</th>
    </tr>
    <% @articles.each do |article| %>
        <tr>
            <td><%= article.title %></td>
            <td><%= article.text %></td>
            <td><%= link_to 'Show', article_path(article)%></td>
        </tr>
    <% end %>
</table>

app/views/articles/new.html.erb
<%= form_for :article, url: articles_path do |f| %>
<% if @article.errors.any? %>
<div id="error_explanation">
    <h2>
        <%= pluralize(@article.errors.count, "error") %>
        prohibited this artcile from being saved:
    </h2>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg %> </li>
        <% end %>
    </ul>
</div>
<% end %>
    <p>
        <%= f.label :title %> <br/>
        <%= f.text_field :title %>
    </p>

    <p>
        <%= f.label :text %> <br/>
        <%= f.text_area :text %>
    </p>

    <p>
        <%= f.submit %>
    </p>
<% end %>

<%= link_to "Back", articles_path %>

app/views/articles/show.html.erb
<p>
    <strong>Title:</strong>
    <%= @article.title %>
</p>
<p>
    <strong>Text: </strong>
    <%= @article.text %>
</p>

<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog1</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to 'My Blog', controller: 'articles' %>